language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - "pip install -r requirements.txt"
script:
  - ./manage.py test
  - coverage run --omit="*virtualenv*","bucketlist*","api/migrations/*" manage.py test
services:
  - postgresql
env:
  global:
    - TRAVIS_BUILD=true
    - DB=postgres
after_success:
    - coveralls
