# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160107_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='bucketlist_id',
            new_name='bucketlist',
        ),
    ]
