# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160107_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bucketlist',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='bucketlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucketlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='bucketlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Bucketlist'),
        ),
    ]
